simplesocial/accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    re_path(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    re_path(r"signup/$", views.SignUp.as_view(), name="signup"),
]

simplesocial/posts/urls.py
from django.urls import re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.urls import re_path, include
from django.contrib import admin
from . import views

urlpatterns = [
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    re_path(r"^test/$", views.TestPage.as_view(), name="test"),
    re_path(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("accounts.urls", namespace="accounts")),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^posts/", include("posts.urls", namespace="posts")),
    re_path(r"^groups/",include("groups.urls", namespace="groups")),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
   

{% endblock %}

simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}